### ISSUE TITLE
feature request: support OpenID Connect

### ISSUE THREAD

**Issue by ericchiang** [dghubble/gologin#10]
This would simplify the Google login. You'd only need one round trip because email is returned as part of the [OpenID Connect ID Token](https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo). You'd also get salesforce, among others.

Please see [ericchiang/oidc](https://github.com/ericchiang/oidc) for the client implementation and let me know if you have any feedback!

**Comment by dghubble** [comment]
Realistically, I don't have plans or desire to add this. Just gonna close.
