### ISSUE TITLE
github: login fails if email isn't public

### ISSUE THREAD

**Issue by ericchiang** [dghubble/gologin#11]
Steps to reproduce:

1. On https://github.com go to "Your profile"
2. Under "Public email" toggle to "Don't show my email address" then "Update profile"
3. On https://whoam.io/ select the github option.
4. Click "authorize application"
4. Am redirected to https://whoam.io/github/callback with "github: unable to get Github User"

**Comment by dghubble** [comment]
Looking into this, it was actually a bug in the whoam.io app's web service signup flow for Github users without emails or with hidden/private emails. The [go-github](https://github.com/google/go-github) User fields are pointers compared with other 3rd-party User/Account structs which use a string email. I've rolled the service fix out so it should work now. Thanks for the report.

No changes to gologin.
