### ISSUE TITLE
Various feature additions

### ISSUE THREAD

**Issue by tamalsaha** [dghubble/gologin#17]
Hi @dghubble,
I have made various changes/additions to gologin library in my fork. I wanted to see if you would be interested in merging them in your version. You can see my changes here: https://github.com/appscode/gologin/commits/master . Here is a summary of changes done:

- [ ] In our case, login server and actual website using social login are hosted on 2 different sub-domains. So, we need to perform an extra redirection after access token is received. This is similar to using a hosted auth service like Auth0. According to my research, one way to do that is to use a coded state parameter (http://stackoverflow.com/a/7722099). So, I renamed StateHandler() to CSRFHandler() and added HostedLogin() handler.
  - [ ] Support HostedLogin Handler
  - [ ] Rename StateHandler() to CSRFHandler() [breaking]
- [ ] Always prompt for account selection in case of Google. If user is logged into multiple Google account, this allows user to select an account to login.
- [ ] Add support for Amazon, Linkedin & Azure AD V2.0
- [ ] For our use case, we need Idp assigned ID/UUID, name, email and profile picture (if available). So, I made changes to Facebook and BitBucket handlers. 
  - [ ] Collect email address for BitBucket
  - [ ] Get user email and profile picture links for facebook login.

If you interested in merging them, I can open prs for them individually.

**Comment by dghubble** [comment]
Additional OAuth1 and OAuth2 providers are welcome. These are essentially convenience handlers around the core oauth1 and oauth2 package handlers.

Fixes to user fetching wrt. to Facebook and Bitbucket are welcome as well. Providers for which I couldn't find quality, canonical Go libraries for the relevant User API (incl. facebook, tumblr, bitbucket) were implemented by just adding a tiny User model and sling call. These have a tendency to get out of date and updates are welcome. The aim is to help apps get enough minimally sufficient info about a user to create their database models, so things like profiles pictures and follower count aren't neccessarily super important. Apps can make requests for rich user details.

I'd like to hold off on the oidc addition until some simplifying changes are made in the client.

The HostedLogin handler looks to me like a success handler that is somewhat specific to your usage. I'm not sure it makes sense in this scope.
