### ISSUE TITLE
Use of ErrorFromContext()

### ISSUE THREAD

**Issue by soulne4ny** [dghubble/gologin#20]
What was desired use of ErrorFromContext()?

The fact that [it returns an error](https://github.com/dghubble/gologin/blob/b5a27e24993f34d9c588bbf4e4050f0d18b4cf57/context.go#L25) even when there is no one in a context is quite intriguing. What could be a way to check if there is an error in the context, let's say, for logging purposes?

**Comment by dghubble** [comment]
Various login providers add request-scoped information about why a login failed, before calling the failure `http.Handler` [example](https://github.com/dghubble/gologin/blob/master/facebook/login.go#L65). If you write a custom failure `http.Handler` you could [do something](https://github.com/dghubble/gologin/blob/master/errors.go#L13) with that error.

It *should* be the case that if your failure handler is called, a meaningful error was written to the context. But you're right, that may not always be the case and certainly using the method on an arbitrary context it won't be the case. You may wish to perform an equality check to be sure the error isn't the default `fmt.Errorf("Context missing error value")`.
