### ISSUE TITLE
Live site is broken?

### ISSUE THREAD

**Issue by prologic** [dghubble/gologin#21]
Tried to authenticate via my Github account and got:

```
rpc error: code = 3 desc = transport: metadata: GCE metadata "instance/service-accounts/default/token" not defined
```

**Comment by dghubble** [comment]
Yeah. I wrote that the example app 2 years ago and have recently been making the clusters more stringent about security (disallow reliance on metadata service https://github.com/poseidon/typhoon/commit/663f37ed6db73f7b51b6cf18a6be11f15ef49e18). Been meaning to replace the example app, but its low on the priority list.

This isn't an issue with gologin.

**Comment by prologic** [comment]
No probs


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by dghubble** [comment]
Removed the link in 542638c84dbaee8022554ff25124c3f7be1c5e2d. I'll restore it eventually.

Thanks for pointing it out.
