### ISSUE TITLE
Feature: Add support any field for facebook user endpoint client

### ISSUE THREAD

**Issue by adrianforsius** [dghubble/gologin#26]
In order to use your library (kudos btw for great work) I would need to fetch more fields than just the email and username on login. The alternative to to another request to the Graph API is not an option and as such I would need support for any field that could possibly be requested from the `/me` endpoint.

I've prepared a PR for this issue, I've read and understood the CONTRIBUTE.md and realize that I might be out of luck if this doesn't align with the goals of this project.

I and the soon to be posted PR suggest:
* Add support for the user client to get any fields
* Make the facebook login handler configurable to use any fields

**Comment by dghubble** [comment]
I'd rather keep the user struct focused on just getting the essential user identifiers. You're given a token with which you may make requests for data like the user's photo and other information.
