### ISSUE TITLE
can't login in localhost due to `insecure login blocked` message

### ISSUE THREAD

**Issue by XanderDwyl** [dghubble/gologin#28]
![error](https://user-images.githubusercontent.com/5339274/37631295-f5709c3c-2c23-11e8-8bd9-57de165ee4a8.png)

**Comment by dghubble** [comment]
This is not a `gologin` bug. Adjust your Facebook settings to whitelist `http://localhost:port/facebook/callback` if that is your intended development callback. In those same settings, you can't have "Enforce HTTPS" checked either if you want to do insecure logins for dev.
