### ISSUE TITLE
Google App Engine Standard & Context

### ISSUE THREAD

**Issue by jaunt** [dghubble/gologin#32]
Hi,

FWIW I'm super impressed with this library.  

I have been unable to get it working on GAE standard without a small change.  

Note: I'm quite fresh to Go so I'm not sure how safe my change is. 

The problem:  Essentially, I found that using just oauth2 to authenticate with a 3rd party, when calling config.Exchange in your oauth2 callback handler, GAE would throw an error after receiving the token: "not an App Engine context". 

My hack solution was to create a new context through the GAE runtime if compiling under GAE standard.  Is there a better way do you think?  And could I get into any trouble with the changes I made?

**oauth2/login.go changes**

...snip

```
		newctx := ContextProvider(req) // create a new GAE context if running in standard environment.
		// use the authorization code to get a Token
		token, err := config.Exchange(newctx, authCode)
		if err != nil {
			ctx = gologin.WithError(newctx, err)
			failure.ServeHTTP(w, req.WithContext(ctx))
			return
		}
		log.Print("Token:")
		log.Print(token)
		ctx = WithToken(newctx, token)
		success.ServeHTTP(w, req.WithContext(ctx))
	}
	return http.HandlerFunc(fn)
```

Two new files under your oauth2 folder:

**new_context_gae_standard.go**

```
// +build appengine

package oauth2

import (
	"context"
	"net/http"

	"google.golang.org/appengine"
)

// ContextProvider returns an app engine context
func ContextProvider(req *http.Request) context.Context {
	return appengine.NewContext(req)
}
```

**new_context_gae_standalone.go**

```
// +build !appengine

package oauth2

import (
	"context"
	"net/http"
)

// ContextProvider returns existing context
func ContextProvider(req *http.Request) context.Context {
	return req.Context()
}
```

**Comment by dghubble** [comment]
I've seen the Google App Engine topic come up a lot across various libraries that use contexts for years now. I appreciate you looking into it and describing your approach. I think this would pull in `google.golang.org/appengine` as a dependency (depending on the vendoring tool). I've never been keen to accommodate Google App engine's choice to use their own special context, its been somewhat of an anti-pattern. Perhaps just carry a fork with this tweak for yourself?

**Comment by dghubble** [comment]
Oh and for your question, yes this seems as good an approach as you're going to find.

**Comment by jaunt** [comment]
Thanks for the notes.

P.S. looks like Google is migrating away from using the the app engine libraries (perhaps they agreed with your anti-pattern sentiment), so moving forward this is a non-issue I guess.

[https://cloud.google.com/appengine/docs/standard/go111/go-differences#migrating-appengine-sdk](url)

**Comment by dghubble** [comment]
That does seem to be a better direction for them and users to move :+1:

Thanks for the link, I think your the markdown goes the a blank url, but https://cloud.google.com/appengine/docs/standard/go111/go-differences#migrating-appengine-sdk works for me.
