### ISSUE TITLE
Needs more GIFs

### ISSUE THREAD

**Issue by shepting** [dghubble/gologin#6]
The `README` is severely lacking in GIFs.

**Comment by shepting** [comment]
I'm still waiting. This issue has not been solved yet.

**Comment by dghubble** [comment]
Very funny Steven. A lack of gifs would indeed be a critical issue requiring immediate action.

However, you'll find a gif in each of the example README's. See the one for [Twitter](https://github.com/dghubble/gologin/tree/master/examples/twitter)
