### ISSUE TITLE
[question] 4.3 Resource Owner Password Credentials Grant

### ISSUE THREAD

**Issue by arvenil** [dghubble/gologin#8]
Is it possible to use this library to perform oauth flow described in https://tools.ietf.org/html/rfc6749#section-4.3 ?

**Comment by dghubble** [comment]
Looks to me like you can call https://godoc.org/golang.org/x/oauth2#Config.PasswordCredentialsToken directly.

I'm not sure of the value of an HTTP handler that passes through password credentials and it doesn't seem appropriate to encourage passing those credentials that way. I haven't used the Password Credential Grant though, perhaps you can elaborate on what you'd like gologin to provide?

**Comment by arvenil** [comment]
"Resource Owner Password Credentials Grant" is in oauth spec for a reason :) You can use it when you trust the client. Of course it's still a matter of "trusting" instead of giving implict grant but there are use cases where this is more tolerable. For example mobile apps, e.g. from Apple store or Google Play store, for concrete service. Again, still better to ask for implict grant, but in case of apps delivered through trusted method (e.g. you can see that given mobile app comes from given vendor) it's acceptable to allow user directly fill credentials in the app.

So, I need "Resource Owner Password Credentials Grant" for mobile authentication that goes directly to our token provider. However we would like to have in future (near one) also possibility to login trough different providers like facebook or google. I can write my own piece of code to make calls to our api, and then use different library for other providers but I wanted to use one tool for all.

When it comes to https://godoc.org/golang.org/x/oauth2#Config.PasswordCredentialsToken I saw it early but it lacks any examples of the usage. In any case I was hoping this library could solve my problems.

**Comment by dghubble** [comment]
I can see this being similar to the Token handler which is just basic handler taking POST arguments and passing them on to an OAuth1 or OAuth2 provider. I may have some time this weekend to add it in.

Are there particular 3rd party providers that support this endpoint that you care about / to test against?

**Comment by dghubble** [comment]
Closed due to lack of response/interest.
